# Generated by Django 2.2.9 on 2019-12-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_auto_20191219_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('following', models.ManyToManyField(related_name='followers', to='many_to_many.TwitterUser')),
            ],
        ),
    ]
